// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnG6BoRvAOKY8X3weDcD_MXF8ot9Dn-0',
    appId: '1:732748302966:web:3496d39d875a928194ad57',
    messagingSenderId: '732748302966',
    projectId: 'movies-app-360f6',
    authDomain: 'movies-app-360f6.firebaseapp.com',
    storageBucket: 'movies-app-360f6.appspot.com',
    measurementId: 'G-J2FBJ044MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlDkqyRuVqydEphzucNgfQWkI10lnxFJ4',
    appId: '1:732748302966:android:05c864c2cdb6df2194ad57',
    messagingSenderId: '732748302966',
    projectId: 'movies-app-360f6',
    storageBucket: 'movies-app-360f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsm8ZuubOhCM4Ed__h8gy-zu_rJNsOxPM',
    appId: '1:732748302966:ios:c6bb8497093d875294ad57',
    messagingSenderId: '732748302966',
    projectId: 'movies-app-360f6',
    storageBucket: 'movies-app-360f6.appspot.com',
    iosBundleId: 'com.example.movesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsm8ZuubOhCM4Ed__h8gy-zu_rJNsOxPM',
    appId: '1:732748302966:ios:c6bb8497093d875294ad57',
    messagingSenderId: '732748302966',
    projectId: 'movies-app-360f6',
    storageBucket: 'movies-app-360f6.appspot.com',
    iosBundleId: 'com.example.movesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnG6BoRvAOKY8X3weDcD_MXF8ot9Dn-0',
    appId: '1:732748302966:web:4cf31dac61b278ab94ad57',
    messagingSenderId: '732748302966',
    projectId: 'movies-app-360f6',
    authDomain: 'movies-app-360f6.firebaseapp.com',
    storageBucket: 'movies-app-360f6.appspot.com',
    measurementId: 'G-J1H88H7QCC',
  );
}
